### ISSUE TITLE
Possible Bug on chunked request: missing crlf after chunk size

### ISSUE THREAD

**Issue by xf4de** [howerj/httpc#1]
As per title, when sending a request with `"Transfer-Encoding: chunked"`, the chunk size is currently sent along side the chunk data. It should be followed by `'\r\n'`. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding)

https://github.com/howerj/httpc/blob/ff16d71c306bc57d2ee5d2c387768197d3336d48/httpc.c#L1015-L1035

Here's a simple fix by copying crlf on `n` buffer (line 1015).
```        
        if (chunky) {
            char n[64 + 1 + 3] = { 0, };
            assert(r < INT_MAX);
            const unsigned l = num_to_str(n, r, 16);
            // EDIT: added crlf after length of chunk
            memcpy(n+l,"\r\n\0",3);
            if (httpc_network_write(h, (unsigned char*)n, l+2) < 0) {
                r = error(h, "write failed");
                break;
            }
        }
```

**Comment by howerj** [comment]
You're right, it is current incorrect. I'll make a fix, thanks for the succinct bug report and fix.
