### ISSUE TITLE
User http headers

### ISSUE THREAD

**Issue by maruncz** [howerj/httpc#15]
Hi, i would like to use this library to query data from influxDB.
To do this i need to add certain headers, but i don't see way to add them in this library.
Am I missing something or I need to modify this library?

**Comment by howerj** [comment]
Adding custom fields to be sent in a request can be done by adding them to `argc`/`argv`. To handle the response you will need to modify the function `httpc_parse_response_field` as there is no way to access the response fields via the libraries API.

**Comment by maruncz** [comment]
thanks, i didn't notice `H` option
