### ISSUE TITLE
post with response

### ISSUE THREAD

**Issue by maruncz** [howerj/httpc#16]
hi, is it possible to easily modify your library to be able to handle post with response body?
i'm trying to implement this api [https://docs.influxdata.com/influxdb/v2/api/#operation/PostQuery](url)
response is tent from server as it should be, but your library is ignoring it.

**Comment by howerj** [comment]
It should be fairly easy to add that in if you want to, I would need to study the code again to work out how, but if you want to have a go you should have no problem.
