### ISSUE TITLE
Hello~ Could you please provide a sample code for how to send messages httpc POST method?

### ISSUE THREAD

**Issue by gadigun** [howerj/httpc#2]
Hello. I am using httpc.
I have a question about how to send messages using httpc POST method.
There doesn't seem to be any explanation for it.
Could you please provide a sample code for how to send messages httpc POST method?

**Comment by howerj** [comment]
There is an example usage of all of the HTTP methods in `main.c`, see the function `httpc_put_cb` (which also is used to perform a POST):

```
static int httpc_put_cb(void *param, unsigned char *buf, size_t length, size_t position) {
	assert(param);
	UNUSED(position);
	FILE *in = param;
	if (length == 0)
		return HTTPC_ERROR;
	const size_t l = fread(buf, 1, length, in);
	if (l < length)
		return ferror(in) ? HTTPC_ERROR : (int)l;
	return l;
}
```

This is in the `yield1` wrapper along with `httpc_post`.
